Rise-Vision/twitter-service

src/app.js, src/config.js, src/redis-cache/index.js, src/redis-otp/datastore.js
Refactored redis connection to redis-cache before adding new redis related code.
- redis-otp finely encapsulates details for connecting to oauth token's provider Redis; this PR does something similar to the cache Redis ( as redis-cache ) as the next PRs will be working with that.
- redis-otp and current Redis code weren't reading the redis service name from configuration, so this PR extracts it to config.
Automated tests work ok.
Manual requests still work ok: http://services-stage.risevision.com/twitter/get-tweets?companyId=121ae986-1b89-40c8-b10b-a64c60fb9e03&username=RiseVision&count=10
Not in production
N/A
=> extract constants, and manager redis-cache connection in own file

src/timelines/index.js, test/unit/timelines.tests.js
Always transform username to lowercase
Twitter screen names are case insensitive, so RiseVision, risevision, RISEVISION refer to the same timeline. In order to avoid creating different cache entries for each one of these keys, this code transforms all usernames to lowercase.
Tested here: http://services-stage.risevision.com/twitter/get-tweets?companyId=121ae986-1b89-40c8-b10b-a64c60fb9e03&username=RISEVISION&count=10
which returns the same as: http://services-stage.risevision.com/twitter/get-tweets?companyId=121ae986-1b89-40c8-b10b-a64c60fb9e03&username=RiseVision&count=10
Unit tests added
Not in production
N/A
=> trasform username parameter to lowercase

src/timelines/data_formatter.js, test/unit/samples/tweets-timeline.js, test/unit/timelines_formatting.tests.js
Created timeline data formatter 
Formatting as follows:
```
{
name: ...,
screenName: ...,
profilePicture: ...,
createdAt: ...,
user: {
description: ...
statuses: ...
followers: ...
},
statistics: {
retweetCount: ...,
likeCount: ...
}
}
```
Ensuring to always account for fields missing since Twitter API is constantly evolving.
The following data will be included in follow up PRs: `quote`, `images`, `text`
Returning this formatted data from a `get-tweets` request also coming in later PR
Twitter Service development
Unit test coverage. Full testing will occur in follow up PR when data is returned from `get-tweets` request
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been …
=> Timeline Data Formatting

src/timelines/data_formatter.js, src/twitter/index.js, test/unit/samples/tweets-timeline.js, test/unit/timelines_formatting.tests.js
Ensuring to include `tweet_mode=extended` in the query params of the _user-timeline_ request in order to contain all information from Tweets that contain more than 140 characters. The response provides `full_text` as a replacement of `text`. Full overview is [here](https://developer.twitter.com/en/docs/tweets/tweet-updates)
Adding `text` value as part of the timeline data formatter. It is the value of `full_text` in the _user-timeline_ response, and if this is not present, falling back on `text` property in the response instead, otherwise it will be `null`. 
Included in the root of the tweet data, for example:
```
{
name: ...,
screenName: ...,
text: ...,
...
}
```
The following data will be included in follow up PRs: `quote`, `images`
Returning this formatted data from a `get-tweets` …
=> Formatting 'text' value from user_timeline data

src/constants.js, src/timelines/data_formatter.js, src/utils.js, test/unit/timelines_formatting.tests.js
Adding `images` value as part of the timeline data formatter. 
Value is an Array of constructed image URLs as per [design](https://docs.google.com/document/d/14wmYT9KGhbkzvd4kYrtO-TiooVtSEv0NrhD5iNp-bew/edit#bookmark=id.uktqgq6bbl0n) 
Acceptable types of media are `photo` and `animated_gif`
Accounting for any missing required fields in _user-timeline_ response, value will be empty Array
Included in the root of the tweet data, for example:
```
{
name: ...,
screenName: ...,
images: [..., ...],
...
}
```
The following data will be included in follow up PRs: `quote`
Returning this formatted data from a `get-tweets` request also coming in later PR
Twitter Service development
Unit test coverage. Full testing will occur in follow up PR when data is returned from `get-tweets` request
- As the …
=> Format images for get-tweets response

src/timelines/data_formatter.js, test/unit/samples/tweets-timeline.js, test/unit/timelines_formatting.tests.js
Adding `quoted` value as part of the timeline data formatter. 
Value is an Object formatted the same as a regular tweet object we respond with, based on the data from the `quoted_status` value in the _user-timeline_ response. As per [design](https://docs.google.com/document/d/14wmYT9KGhbkzvd4kYrtO-TiooVtSEv0NrhD5iNp-bew/edit#bookmark=id.gz4d6b4ahj31) 
Accounting for any missing required fields in _user-timeline_ response, value will be `null`
Only providing top level quoted value, no further nested quoted tweets. 
Structured in the response as per example:
```
{
name: ...,
screenName: ...,
quoted: {
name: ...,
screenName: ...,
...
},
...
}
```
Returning this fully formatted data from a `get-tweets` request coming in follow up PR
Twitter Service development
Unit test coverage. Full testing …
=> Format quoted value for get-tweets response

src/timelines/index.js, test/unit/samples/tweets-2.js, test/unit/timelines.tests.js
Transforming data from _user-timeline_ API response to our custom format for returning in `get-tweets` endpoint response. 
Twitter Service development
Tested with _@ mashable_ to catch an _images_ populate and also _@ SarahKSilverman_ to catch a _quoted_ get populated.
https://services-stage.risevision.com/twitter/get-tweets?companyId=cb73b359-b827-4e38-9893-9ee28d8e5676&username=mashable&count=10
https://services-stage.risevision.com/twitter/get-tweets?companyId=cb73b359-b827-4e38-9893-9ee28d8e5676&username=SarahKSilverman&count=10
Will also test with other accounts but this appears to be enough to validate. 
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been …
=> Respond with formatted data for get-tweets endpoint

src/timelines/index.js, test/unit/timelines_cache.tests.js
Return cached tweets if they are available when loading flag is on.
Part of Twitter service design.
The loading flag was forced for a username. Then a request was done for that username and it returned the expected HTTP response:
The 30 seconds expiration indicates that the client should request the updated Tweets soon to get the updated tweet list.
Not on production.
N/A
=> return cached tweets if loading flag is on

.eslintrc.json, package-lock.json, package.json, src/app.js, src/config.js, src/core/index.js, src/timelines/index.js, src/utils.js, test/unit/core.tests.js, test/unit/timelines.tests.js
First step towards migrating to using `presentationId` and `componentId. This adds a new endpoint but leaves the existing one untouched, in order to not affect other tasks.
Next set of PRs will include environment handling and caching (separate PRs)
Part of our epic.
It can be validated here: https://services-stage.risevision.com/twitter/get-presentation-tweets?presentationId=21c97752-0b8b-4a0c-852c-83c0471a3e00&componentId=rise-data-twitter-01
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release …
=> Use presentationId and componentId for getTweets

.circleci/config.yml, package-lock.json, package.json, src/config.js, src/core/index.js, src/redis-cache/api.js, src/timelines/index.js, src/utils.js, test/unit/core.tests.js
These changes complete part 2 of 2 sets of changes required for implementation of not exposing company id in get tweets endpoint. Design doc [here](https://docs.google.com/document/d/1AigkbBu1aJSO4nrZjMpfOt6F76e43vgZPX_5JyPoSJw/edit#heading=h.4ve2jnvd4agp). Part 1 was PR #37  
Revised endpoint `get-presentation-tweets` is expecting _presentation id_, _component id_, and _hash_. The _hash_ is constructed with `presentationId` + `componentId` + `username` as a SHA1 hash value.
The endpoint calls Core to retrieve presentation in order to get company id which is required for the flow of verifying Twitter credentials and subsequently getting tweets. 
When presentation data is retrieved from Core, the data is cached to avoid hitting Core every time. In Redis the _presentationId_ -> _companyId_ …
=> Cache presentation data from Core

.eslintrc.json, src/core/index.js, src/timelines/index.js, test/unit/core.tests.js, test/unit/timelines.tests.js
Implement a new required query param `useDraft` for `get-presentation-tweets` endpoint 
Apply `useDraft` as query param when making request to Core for retrieving presentation data. 
This is part 1 of 2 changes to support Twitter Component running on Preview vs. Display. 
When running on Preview, our Service requires _revised_ (aka draft) presentation data to ensure it leverages the latest unpublished template attribute data. This is acquired by `useDraft` with a value of `true` in the Core request. 
When running on a Display, our our Service requires _published_ presentation data to ensure it leverages only the published template attribute data. This is acquired by `useDraft` with a value of `false` in the Core request.
Published: (username is CNN) …
=> Add useDraft query param for get-presentation-tweets endpoint

src/blueprint/index.js, src/config.js, src/core/index.js, test/unit/blueprint.tests.js, test/unit/core.tests.js, test/unit/samples/blueprint.js
When username is not available from Core presentation data, load template blueprint with product code received from presentation data.
With template blueprint data, extract the username value from the appropriate component based on component id.
This is part 2 of 2 changes to support Twitter Component running on Preview vs. Display. 1st set of change are here - https://github.com/Rise-Vision/twitter-service/pull/39
When a template is initially selected by a user and they view it in Template Editor, there is no attribute data available. Hence, the presentation data from Core will not provide the required username needed for retrieving tweets. In this situation, we now fall back to checking `username` in template blueprint. 
Tested via Apps staging by selecting _Example Twitter Component_ …
=> Get username value from blueprint when not available in presentation data

src/app.js, src/timelines/index.js
Deprecate previous `get-tweets` endpoint
To keep our API clean
N/A
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
=> Deprecate previous endpoint

src/app.js, src/core/index.js, src/timelines/index.js, test/unit/core.tests.js, test/unit/timelines.tests.js
Provide new endpoint `get-tweets` with expected params `presentationId`, `componentId`, and  `username`. Also supports optional `count` param. 
This is the initial implementation and logic for supporting an endpoint to get tweets that takes a username. Follow up PR will implement expecting the `username` encrypted and handle decrypting it via public/private keys. 
These changes have been required to account for an issue with `get-presentation-tweets` endpoint where a race condition is occurring between presentation data being saved to Core via Apps attribute editor changes, and retrieving presentation data from Core in the Service in order to obtain the component instance username (as well as company id). 
Unit test coverage as well as testing directly against service. …
=> Implement new endpoint to handle username param

src/timelines/index.js, src/timelines/mock-data.js, test/unit/timelines.tests.js
Send mock data in response when request has presentationId value as `demo`.
Component id, username, and count will all be ignored. 
This is to resolve rise-data-twitter e2e test infrastructure due to an actual presentation id not being associated with the rise-data-twitter e2e html page (its scheduled as a URL Item). The url item will have `&presentationId=demo` appended so the component requests to the service with that value and the service responds with mock data. 
Tested against service. 
https://services-stage.risevision.com/twitter/get-tweets?presentationId=demo&componentId=rise-data-twitter-01&username=toronto&count=3
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) …
=> Implement providing mock data based on 'demo' presentation id

src/app.js, src/timelines/index.js
- Remove `get-tweets` endpoint 
- Rename `handleGetTweetsSecureEncryptedRequest ` to `handleGetTweetsEncryptedRequest `
Code cleanup
Manually on stage-8 and with existing unit tests.
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
=> Remove get-tweets endpoint

.circleci/config.yml, package.json, src/config.js, src/redis-cache/index.js, src/redis-otp/datastore.js
Update conditionals that are dependent on NODE_ENV with values 
- `dev`: local development
- `test`: messaging-service-staging cluster
- `prod`: messaging-service-prod cluster
These environments also dictate which Core presentation/content endpoint url to use. 
CCI config updated to deploy to production cluster and ensure staging and production deployments have the appropriate NODE_ENV value applied
Twitter release
Validated all working as expected on apps staging at https://apps-stage-8.risevision.com/templates/edit/442f3ffd-ecb7-4c3c-958a-8401fcf2b4ae/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443
Validation on production will occur when all parts are deployed
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release …
=> Deploy to production cluster

src/timelines/data_formatter.js, src/timelines/mock-data.js, test/unit/timelines_formatting.tests.js
Remove __normal_ from the profile picture url so the largest size is targeted
Creative need largest size for template development
Note: if validating yourself, be sure to use a handle you haven't used before so that service/component doesn't provide cached data. 
https://pbs.twimg.com/profile_images/935885263955546112/7lobzXaB.jpg
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
n/a
=> Ensure largest version of profile picture is provided

src/constants.js, src/twitter/index.js, test/unit/credentials.tests.js, test/unit/timelines.tests.js, test/unit/twitter.tests.js
When checking specifically for an invalid or expired token response error from API _verify-credentials_ endpoint, now ensuring to check for code `89` as defined in the API response codes documentation - https://developer.twitter.com/en/docs/basics/response-codes
Previously checking the error response `message` was brittle as the API could change the message value. 
Unit tests. Smoke tested service working as expected on Apps staging. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/36003 …
=> Base invalid token detection on API code instead of message String

src/timelines/data_formatter.js, test/unit/timelines_formatting.tests.js
Preventing a retweet text from being truncated by checking for existence of `retweeted_status` and if present then construct the text to provide from the `full_text` property of `retweeted_status`. 
Also injecting the usual retweet prefix including username from the `retweeted_status`. The text is constructed as so:
`RT @ __user__: __full text__`
If _full_text_ not present in `retweeted_status`, then it falls back on _text_
We don't want to truncate any tweet text, regardless of being a regular tweet, retweet, or quoted tweet. 
Tested staging service on staging apps 8. Screenshots of example retweets below:
https://www.screencast.com/t/28Ih5ptExqw1
https://www.screencast.com/t/R8bqxCgV1qFq
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release …
=> Support full text from a retweet

src/timelines/data_formatter.js, test/unit/timelines_formatting.tests.js
Populating text quote tweets with text that has all occurrences of Twitter API shortened urls in it removed. 
Example shortened url - `https://t.co/LA5tgQEtU8` 
The regular expression used `/https:\/\/t.co\/\S+/gi` is broken down as follows:
`/https:\/\/t.co\/\` - matching urls that start with https://t.co/
`S+/` - matches all non-whitespace characters (to the end of the url)
`gi` - matches all case insensitive occurrences
This is to address issue https://github.com/Rise-Vision/rise-data-twitter/issues/36
For a quote tweet, a shortened url is appended which is a link to the quote. 
This url is irrelevant when displayed in a template and is creating visual pollution. It is not clickable and provides no value since the original tweet is displayed on screen.  
Staging service on Apps staging …
=> Remove Twitter API generated urls from quote tweets
